# Simple Scribe Ledger Configuration
# This is the default configuration file

[node]
# Unique identifier for this node (must be > 0)
id = 1
# Address for this node
address = "127.0.0.1"
# Data directory for storage
data_dir = "./node-1"

[network]
# Address to listen on for client connections
listen_addr = "127.0.0.1:8001"
# Port for client HTTP API
client_port = 8001
# Port for Raft consensus communication
raft_port = 9001

[storage]
# Maximum size of a data segment in bytes (64MB)
segment_size = 67108864
# Maximum cache size in bytes (256MB)
max_cache_size = 268435456

[consensus]
# Election timeout minimum in milliseconds
election_timeout_min = 1500
# Election timeout maximum in milliseconds
election_timeout_max = 3000
# Heartbeat interval in milliseconds (must be less than election timeout)
heartbeat_interval_ms = 300

[api]
# Write timeout in seconds
write_timeout_secs = 30
# Read timeout in seconds
read_timeout_secs = 10
# Maximum batch size for write operations
max_batch_size = 100
# Cache capacity for hot data
cache_capacity = 1000

[discovery]
# Heartbeat interval in milliseconds
heartbeat_interval_ms = 500
# Failure detection timeout in milliseconds
failure_timeout_ms = 1500
