# Simple Scribe Ledger Configuration
# This is the default configuration file

[node]
# Unique identifier for this node (must be > 0)
id = 1
# Address for this node
address = "127.0.0.1"
# Data directory for storage
data_dir = "./node-1"

[network]
# Address to listen on for client connections
listen_addr = "127.0.0.1:8001"
# Port for client HTTP API (default: 8000 + node_id)
client_port = 8001
# Port for Raft consensus communication (default: 9000 + node_id)
raft_port = 9001

[storage]
# Maximum size of a data segment in bytes (64MB)
segment_size = 67108864
# Maximum cache size in bytes (256MB)
max_cache_size = 268435456

# S3 storage configuration (optional)
# Uncomment and configure to enable S3 archival
# [storage.s3]
# bucket = "scribe-ledger"
# region = "us-east-1"
# # For MinIO or custom S3-compatible endpoint
# endpoint = "http://localhost:9000"
# access_key_id = "minioadmin"
# secret_access_key = "minioadmin"
# # Enable path-style for MinIO (default: false)
# path_style = true
# # Connection pool size (default: 10)
# pool_size = 10
# # Request timeout in seconds (default: 30)
# timeout_secs = 30
# # Maximum retry attempts (default: 3)
# max_retries = 3

[consensus]
# Election timeout minimum in milliseconds (default: 1500)
election_timeout_min = 1500
# Election timeout maximum in milliseconds (default: 3000)
election_timeout_max = 3000
# Heartbeat interval in milliseconds (must be less than election timeout, default: 300)
heartbeat_interval_ms = 300

[api]
# Write timeout in seconds (default: 30)
write_timeout_secs = 30
# Read timeout in seconds (default: 10)
read_timeout_secs = 10
# Maximum batch size for write operations (default: 100)
max_batch_size = 100
# Cache capacity for hot data (default: 1000)
cache_capacity = 1000

[discovery]
# Heartbeat interval in milliseconds (default: 500)
heartbeat_interval_ms = 500
# Failure detection timeout in milliseconds (default: 1500)
failure_timeout_ms = 1500
# UDP port for discovery broadcasts (default: 17946)
discovery_port = 17946
# Broadcast address for discovery (default: 255.255.255.255 for LAN-wide discovery)
# Use specific subnet broadcast for limited scope (e.g., 192.168.1.255)
broadcast_addr = "255.255.255.255"
# Cluster secret for cross-network authentication (optional)
# Nodes must have matching secrets to join the same cluster
# cluster_secret = "your-secret-token-here"
