name: Benchmark

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build benchmarks
      run: cargo build --release --benches
    
    - name: Run storage benchmarks
      run: cargo bench --bench storage_benchmark
    
    - name: Run async storage benchmarks
      run: cargo bench --bench async_storage_benchmark
    
    - name: Run simple HTTP benchmarks
      run: cargo bench --bench simple_http_benchmark
    
    - name: Setup MinIO for S3 benchmarks
      run: |
        docker run -d -p 9000:9000 -p 9001:9001 \
          --name minio \
          -e "MINIO_ROOT_USER=minioadmin" \
          -e "MINIO_ROOT_PASSWORD=minioadmin" \
          quay.io/minio/minio server /data --console-address ":9001"
        
        # Wait for MinIO to be ready
        for i in {1..30}; do
          if curl -sf http://localhost:9000/minio/health/live > /dev/null 2>&1; then
            echo "MinIO is ready"
            break
          fi
          echo "Waiting for MinIO... ($i/30)"
          sleep 2
        done
        
        # Install MinIO client
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        sudo mv mc /usr/local/bin/
        
        # Configure MinIO
        mc alias set myminio http://localhost:9000 minioadmin minioadmin
        mc mb myminio/benchmark-bucket || true
        mc mb myminio/scribe-test-bucket || true
    
    - name: Run S3 storage benchmarks (Task 6.1)
      env:
        S3_BUCKET: benchmark-bucket
        S3_REGION: us-east-1
        S3_ENDPOINT: http://localhost:9000
        S3_ACCESS_KEY_ID: minioadmin
        S3_SECRET_ACCESS_KEY: minioadmin
        S3_PATH_STYLE: "true"
      run: cargo bench --bench s3_storage_benchmark
    
    - name: Run archival benchmarks (Task 6.2 & 6.3)
      env:
        S3_BUCKET: scribe-test-bucket
        S3_REGION: us-east-1
        S3_ENDPOINT: http://localhost:9000
        S3_ACCESS_KEY_ID: minioadmin
        S3_SECRET_ACCESS_KEY: minioadmin
        S3_PATH_STYLE: "true"
      run: cargo bench --bench archival_benchmark
    
    - name: Run performance tests
      run: |
        cargo run --release --bin performance_test
        cargo run --release --bin optimized_performance_test
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: benchmark-results
        path: |
          target/criterion/
          *.txt
        retention-days: 30
